SET REFERENTIAL_INTEGRITY FALSE
TRUNCATE TABLE "FeedMetaData" RESTART IDENTITY
TRUNCATE TABLE "Feed" RESTART IDENTITY
TRUNCATE TABLE "Profile" RESTART IDENTITY
TRUNCATE TABLE "User" RESTART IDENTITY
SET REFERENTIAL_INTEGRITY TRUE